package exceptionHandling2;

public class ThrowPractise3 {

	public static void main(String[] args) {
		
		
		throw new ArithmeticException("rabin this is exception");
		//System.out.println("hello");//remove

	}//after throw the code will not excetued

}
